version: '3.4'

services:
  basketdb:
    container_name: basketdb
    restart: always
    ports:
        - 6379:6379

  basket.api:
    container_name: basketapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:Redis=basketdb:6379"
    ports:
      - "8000:80"
